name: Publish to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish on Version Change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: RICADO.Ini.csproj
        TAG_COMMIT: true
        NUGET_KEY: ${{secrets.GITHUB_TOKEN}}
        NUGET_SOURCE: https://nuget.pkg.github.com/ricado-group
